name: Android CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: NO_GPG_SIGN=true ./gradlew --stacktrace build javadocJar publishToMavenLocal

      - name: Upload jars
        uses: actions/upload-artifact@v3
        with:
          name: maven-repo
          path: ~/.m2/repository/com/yubico/yubikit/

  check:
    runs-on: ubuntu-latest

    permissions:
      checks: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: NO_GPG_SIGN=true ./gradlew --stacktrace check test

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            ./**/build/test-results/test/*.xml

      - name: Publish SpotBugs reports
        uses: lcollins/spotbugs-github-action@v2.0.0
        with:
          path: ./**/build/reports/spotbugs/*.xml

      - name: Upload build reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: build-reports
          path: ./*/build/reports/*
