name: "SpotBugs"

on:
  push:
    branches: [adamve/spotbugs-reports-v3]
  pull_request:
    branches: [adamve/spotbugs-reports-v3]
  schedule:
    - cron: "25 16 * * 0"

jobs:
  analyze:
    name: SpotBugs Analyze

    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ["java"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build with Gradle
        run: ./gradlew spotbugsRelease spotbugsMain

      - name: Fix SARIF
        run: >-
          for module in \
            "android" \
            "AndroidDemo" \
            "core" \
            "fido" \
            "management" \
            "oath" \
            "openpgp" \
            "piv" \
            "support" \
            "testing" \
            "yubiotp";
          do
            SARIF="./build/spotbugs/spotbugs-$module.sarif"

            cat $SARIF |
              jq '.runs |= map( if .taxonomies == [null] then .taxonomies = [] else . end)' |
              jq ".runs[].results[].locations[].physicalLocation.artifactLocation.uri |= \"$module/src/main/java/\" + ." |
              jq '.runs[].tool.driver.rules |= map( . += { fullDescription: { text: .shortDescription.text } } )' |
              jq '.runs[].tool.driver.rules |= map( . += { help: { text: .helpUri } } )' |
              jq -c '.' > $SARIF.json
            mv $SARIF.json $SARIF
          done

      - name: upload SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: build/spotbugs/
          category: spotbugs-analysis
